--- 
before_install: 
  - "docker build -t mpati007/docker-react -f Dockerfile.dev ."
deploy: 
  access_key_id: $AWS_ACCESS_KEY
  app: docker
  bucker_name: elasticbeanstalk-us-west-2-640438245460
  bucket_path: docker
  env: Docker-env
  provider: elasticbeanstalk
  region: us-west-2
  secret_access_key: $AWS_SECRET_KEY
  true: 
    branch: master
language: generic
script: 
  - "docker run -e CI=true mpati007/docker-react npm run test"
services: 
  - docker
sudo: required
